FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

# Copy the Maven POM file
COPY pom.xml .

# Copy source code
COPY src ./src

# Expose port
EXPOSE 8080

# Start Spring Boot in dev mode
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"] 